# Project information
site_name: TRecover
site_description: A Python library to train Transformer neural network for keyless reading task.
site_author: Alexander Shulga

# Repository
repo_url: https://github.com/alex-snd/TRecover
repo_name: alex-snd/TRecover
edit_uri: "" # disables edit button

# Copyright
copyright: Copyright &copy; 2022

# Social media
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alex-snd
    - icon: fontawesome/brands/telegram
      link: https://t.me/alexsnd
    - icon: fontawesome/solid/at
      link: mailto:alexandershulga.sh@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/alex-snd
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/alexsnd0

# Configuration
theme:
  name: material
  logo: static/images/logo.png
  favicon: static/images/favicon.ico
  font:
    text: Georgia
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
#    - toc.integrate
  icon:
    repo: fontawesome/brands/github

# Extra CSS
extra_css:
  - static/css/custom.css

# Extensions
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - pymdownx.tabbed # content tabs
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
      watch:
        - src/trecover

# Page tree
nav:
  - Home: index.md
  - Reference:
    - CLI: src/trecover/app/cli/trecovercli.md
