# Project information
site_name: TRecover
site_description: A Python library to train Transformer neural network for keyless reading task.
site_author: Alexander Shulga

# Repository
repo_url: https://github.com/alex-snd/TRecover
repo_name: alex-snd/TRecover
edit_uri: "" # disables edit button

# Copyright
copyright: Copyright &copy; 2022

# Social media
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alex-snd
    - icon: fontawesome/brands/telegram
      link: https://t.me/alexsnd
    - icon: fontawesome/solid/at
      link: mailto:alexandershulga.sh@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/alex-snd
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/alexsnd0

# Configuration
theme:
  name: material
  logo: static/images/logo.png
  favicon: static/images/favicon.ico
  font:
    text: Georgia
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.instant
    - navigation.tracking
    - content.tabs.link
    - navigation.top
  icon:
    repo: fontawesome/brands/github

# Extra CSS
extra_css:
  - static/css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - meta
  - abbr
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - pymdownx.tabbed: # content tabs
      alternate_style: true
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: true
            show_category_heading: false
            separate_signature: true
            members_order: source

      watch:
        - src/trecover

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting_started/installation.md
    - Data: getting_started/data.md
    - Train: getting_started/train.md
  - Objective:
    - Task definition: objective/task_definition.md
    - Related work: objective/related_work.md
  - Demo: demo.md
  - Reference:
    - CLI:
      - src/trecover/app/cli/index.md
      - Download : src/trecover/app/cli/download.md
      - Train : src/trecover/app/cli/train.md
      - Mlflow : src/trecover/app/cli/mlflow.md
      - Dashboard : src/trecover/app/cli/dashboard.md
      - API : src/trecover/app/cli/api.md
      - Worker : src/trecover/app/cli/worker.md
      - Broker : src/trecover/app/cli/broker.md
      - Backend : src/trecover/app/cli/backend.md
    - API:
      - src/trecover/app/api/index.md
      - Schemas : src/trecover/app/api/schemas.md
      - Celery Tasks : src/trecover/app/api/backend/tasks.md
    - Utils:
        - Beam Search : src/trecover/utils/beam_search.md
        - CLI : src/trecover/utils/cli.md
        - Docker : src/trecover/utils/docker.md
        - Inference : src/trecover/utils/inference.md
        - Model : src/trecover/utils/model.md
        - Train : src/trecover/utils/train.md
        - Transform : src/trecover/utils/transform.md
        - Visualization : src/trecover/utils/visualization.md

