[dashboard]
host = "localhost"
port = 8000
loglevel = 'info'

[api]
host = "localhost"
port = 8001
loglevel = 'info'
concurrency = 1

[worker]
name = "TRecoverWorker"
pool = "solo"
loglevel = "info"
concurrency = 1
broker_url = "pyamqp://guest@localhost:5672"
backend_url = "redis://localhost:6379"

[broker]
port = 5672
ui_port = 15672
auto_remove = false

[backend]
port = 6379
auto_remove = false