version: "3.3"

x-common-env: &common-env
  CUDA: ${CUDA:-True}
  CELERY_BROKER: pyamqp://guest@rabbitmq:5672
  CELERY_BACKEND: redis://redis:6379


services:

  dashboard:
    container_name: dashboard
    image: zreader-dashboard:latest

    build:
      context: ../..
      dockerfile: ./docker/file/dashboard

    environment:
      STREAMLIT_PORT: ${STREAMLIT_PORT:-8000}
      FASTAPI_HOST: api
      FASTAPI_PORT: ${FASTAPI_PORT:-8001}

    ports:
      - ${STREAMLIT_PORT:-8000}:${STREAMLIT_PORT:-8000}

    restart: always

    depends_on:
      - api
      - worker
      - redis
      - rabbitmq


  api:
    container_name: api
    image: zreader-api:latest

    build:
      context: ../..
      dockerfile: ./docker/file/api

    environment:
      <<: *common-env
      FASTAPI_PORT: ${FASTAPI_PORT:-8001}
      FASTAPI_WORKERS: ${FASTAPI_WORKERS:-1}

    ports:
      - ${FASTAPI_PORT:-8001}:${FASTAPI_PORT:-8001}

    restart: always

    depends_on:
      - worker
      - redis
      - rabbitmq


  worker:
    image: zreader-worker:latest

    build:
      context: ../..
      dockerfile: ./docker/file/worker

    environment:
      <<: *common-env
      CELERY_WORKERS: ${CELERY_WORKERS:-1}

    restart: always

    depends_on:
      - redis
      - rabbitmq


  redis:
    container_name: redis
    image: ${BACKEND_IMAGE:-redis:6.2}
    restart: always
    expose:
      - 6379


  rabbitmq:
    container_name: rabbitmq
    image: ${BROKER_IMAGE:-rabbitmq:3.9.8-management}
    restart: always
    expose:
      - 5672