name: documentation
on:
  push:
    branches:
      - master

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version