name: Sync to Hugging Face hub
on:
  push:
    branches: 
      - huggingface

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'huggingface'
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://alex-snd:$HF_TOKEN@huggingface.co/spaces/alex-snd/ZReader HEAD:main
